openapi: '3.0.2'
info:
  title: Storage Service for Visual Content 
  version: '1.0'
servers:
  - url: https://storage-service-7x5inv6roa-lz.a.run.app
paths:
  /store:
    post:
      summary: Store the created images.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  title:
                    type: string
                  img_b64:
                    type: string 
                    description: the image converted to base64
      responses:
        '200':
          description: An image object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  url:
                    type: string
                    example: https://storage.googleapis.com/sde-storage-bucket/simone__sde.itA_website_that_uses_machine_learning_to_create_blog_posts_and_images.jpeg
        '401':
          description: Invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Unauthorized